# FROM ubuntu:20.04

# RUN apt update
# RUN apt install -y software-properties-common
# RUN add-apt-repository ppa:deadsnakes/ppa
# RUN apt install python3.8

FROM jee161209/build-tutorial

RUN apt update
RUN apt install -y python3-pip