# -*- coding: utf-8 -*-
"""YouTube API Snapshot extraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X4Ffxv8pzZZzTiihD9oH7BBjGCm2jGLP
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings(action = 'ignore')

import cv2

from google.colab import drive
drive.mount('/content/drive')

# cap = cv2.VideoCapture('/content/drive/MyDrive/Youtube_API/Mukbang/SUB)과즙팡팡 과일 먹방 !🍒🍓🍋 메론 망고 파인애플 용과 대왕딸기 귤 (feat요거트씨리얼) fruit mukbang ASMR melon mango strawberry.mp4')

# while(cap.isOpened()):
#   ret, frame = cap.read()
#   gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
#   cv2.imshow('frame', gray)

#   if cv2.waitKey(1) & 0xFF == ord('q'):
#     break

# cap.release()
# cv2.destroyAllWindows()

import glob # 사용자가 제시한 조건에 맞는 파일명을 리스트 형식으로 제시

mb_list = glob.glob('/content/drive/MyDrive/Youtube_API/Mukbang/*.webm')
gm_list = glob.glob('/content/drive/MyDrive/Youtube_API/Game/*.webm')

# import os
# os.listdir('/content/drive/MyDrive/Youtube_API/Mukbang/')

mb_list[16]

len(gm_list)

for index, vid in enumerate(mb_list):
  try:
    cap = cv2.VideoCapture(mb_list[index])

    sample_num = 0
    captured_num = 0

    if not cap.isOpened():
      print("Cannot open the cap")
    else:
      pass

    while(cap.isOpened()):
      ret, frame = cap.read()
      sample_num += 1

      if not ret:
        print(ret)
        break

      if sample_num == 60:
        captured_num += 1
        cv2.imwrite('/content/drive/MyDrive/Youtube_API/Mukbang_img/'+ str(index) + '_' +str(captured_num) + '.jpg', frame) # 으잉?
        sample_num = 0

    cap.release()


  except Exception as e:
    print(e)

# vid_title = '[오버워치] 꼭 기억해야 할 메르시 수호천사 꿀팁 5가지 단 3분 메르시 장인이 되는 방법'
# # cap = cv2.VideoCapture('/content/drive/MyDrive/Youtube_API/Mukbang/' + vid_title + '.mp4')


cap = cv2.VideoCapture('/content/drive/MyDrive/Youtube_API/Mukbang/SUB)매운 해물찜 먹방🔥 낙지 문어 전복 갑오징어 새우에 당면까지 리얼사운드  Spicy Seafood Mukbang Asmr.webm')

sample_num = 0
captured_num = 0

# if not cap.isOpened():
#   print("Cannot open the cap")
# else:
#   raise Exception("capture is not opened")

# while(cap.isOpened()):
for i in range(99999999999999):

  if not cap.isOpened():
    # print("Capture object is not opened")
    raise Exception("capture is not opened")
    break

  ret, frame = cap.read()
  print(f"success: {ret}, frame shape: {frame.shape}")
  sample_num += 1

  if not ret:
    print(ret)
    break

  if sample_num == 60:
    captured_num += 1
    # cv2.imwrite('/content/drive/MyDrive/Youtube_API/Game_img/'+vid_title+str(captured_num) + '.jpg', frame)///
    cv2.imwrite('/content/drive/MyDrive/Youtube_API/test/'+str(captured_num) + '.jpg', frame)
    sample_num = 0


cap.release()

# # video 저장 

# cap = cv2.VideoCapture(0)

# fourcc = cv2.VideoWriter_fourcc(*'DIVX')
# out = cv2.VideoWriter('test.avi', fourcc, 25.0, (640, 400))

# while (cap.isOpened()):
#   ret, frame = cap.read()

#   if ret:
#     frame = cv2.flip(frame, 0)

#     out.write(frame)

#     cv2.imshow('frame', frame)

#     if cv2.waitKey(0) & 0xFF == ord('q'):
#       break

# cap.release()
# out.release()
# cv2.destroyAllWindows()

gm_list

"""### Game 영상 for문 다운받는 코드"""

for index, vid in enumerate(gm_list):
  try:
    cap = cv2.VideoCapture(gm_list[index])

    sample_num = 0
    captured_num = 0

    if not cap.isOpened():
      print("Cannot open the cap")
    else:
      pass

    while(cap.isOpened()):
      ret, frame = cap.read()
      sample_num += 1

      if not ret:
        print(ret)
        break

      if sample_num == 60:
        captured_num += 1
        cv2.imwrite('/content/drive/MyDrive/Youtube_API/Game_imgs/'+ str(index) + '_' +str(captured_num) + '.jpg', frame) # 으잉?
        sample_num = 0

    cap.release()


  except Exception as e:
    print(e)

