# -*- coding: utf-8 -*-
"""YouTube API Snapshot extraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X4Ffxv8pzZZzTiihD9oH7BBjGCm2jGLP
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings(action = 'ignore')

import cv2

# from google.colab import drive
# drive.mount('/content/drive')

import glob # 사용자가 제시한 조건에 맞는 파일명을 리스트 형식으로 제시


gm_list = glob.glob('/content/drive/MyDrive/Youtube_API/Game/*.webm') #### 경로 변경 

"""### Game 영상 snapshot 다운받는 코드"""

for index, vid in enumerate(gm_list):
  try:
    cap = cv2.VideoCapture(gm_list[index])

    sample_num = 0
    captured_num = 0

    if not cap.isOpened():
      print("Cannot open the cap")
    else:
      pass

    while(cap.isOpened()):
      ret, frame = cap.read()
      sample_num += 1

      if not ret:
        print(ret)
        break

      if sample_num == 60:
        captured_num += 1
        cv2.imwrite('/content/drive/MyDrive/Youtube_API/Game_imgs/'+ str(index) + '_' +str(captured_num) + '.jpg', frame) # 경로 변경 
        sample_num = 0

    cap.release()


  except Exception as e:
    print(e)


