# -*- coding: utf-8 -*-
"""Collecting Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HzLOThQz9PFlvIhAjyCq_jXHcTEBrwtM
"""

"""## Video Download"""

pip install pytube3

pip install --upgrade pytube

from pytube import YouTube

vlog_videos = []
edu_videos = []

for i in range(1,3):
  var = globals()['video' + str(i)]
  vlog_videos.extend(var.values())

  var2 = globals()['video' + str(i+2)]
  edu_videos.extend(var2.values())

print(len(vlog_videos))
print(len(edu_videos))

link1 = "https://www.youtube.com/watch?v="

for id in vlog_videos:
  link = link1 + str(id)
  yt = YouTube(link)

  ys = yt.streams.filter(only_video=True, file_extension='mp4')

  for s in ys :
    try :
      s.download('/content/drive/MyDrive/PROJECT/Youtube_data/vlogs')  # need to change path
    except :
      print(f"Where id {id} stream {s}")

for id in edu_videos:
  link = link1 + str(id)
  yt = YouTube(link)

  ys = yt.streams.filter(only_video=True)

  for s in ys :
    try :
      s.download('/content/drive/MyDrive/PROJECT/Youtube_data/education')
    except :
      print(f"Where id {id} stream {s}")

